# Use tiangolo's FastAPI base image
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

# Set working directory
WORKDIR /app

# Copy and install Python dependencies first to leverage Docker caching
COPY ./requirements.txt /app/requirements.txt

# Install system dependencies and Python dependencies in one step
RUN apt-get update && \
    apt-get install -y libgl1-mesa-dev cmake && \
    pip install --no-cache-dir -r requirements.txt

# Set environment variable
ENV SERVER_BASE_URL="http://localhost:8000/"

# Copy application files
COPY ./Database/. /app/Database
COPY ./output/. /app/output

# Expose the port that Uvicorn will run on
EXPOSE 80

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
